<?php

namespace Database\Seeders;

use App\Models\Puzzle;
use App\Models\PuzzleCategory;
use Illuminate\Database\Seeder;

class PuzzleSeeder extends Seeder
{
    public function run(): void
    {
        $logic = PuzzleCategory::where('slug', 'logic')->first();
        $math = PuzzleCategory::where('slug', 'math')->first();
        $language = PuzzleCategory::where('slug', 'language')->first();
        $general = PuzzleCategory::where('slug', 'general-knowledge')->first();
        $visual = PuzzleCategory::where('slug', 'visual')->first();

        $samples = [

            // ===== ألغاز منطقية =====
            [
                'puzzle_category_id' => $logic->id,
                'title' => 'الأخوة الثلاثة',
                'type' => 'text',
                'difficulty' => 'easy',
                'prompt' => 'لدى أحمد ثلاثة إخوة، وكل أخ لديه أخت واحدة. كم عدد الأخوات في العائلة؟',
                'answer_raw' => 'واحدة',
                'hint' => 'فكر: هل كل أخ يتكلم عن أخت مختلفة، أم نفس الأخت؟',
                'gem_reward' => 5,
            ],
            [
                'puzzle_category_id' => $logic->id,
                'title' => 'الشيء الذي يكبر بالأخذ منه',
                'type' => 'text',
                'difficulty' => 'easy',
                'prompt' => 'ما الشيء الذي كلما أخذت منه كبر؟',
                'answer_raw' => 'الحفرة',
                'hint' => 'فكّر بشيء تحفره بالأرض.',
                'gem_reward' => 5,
            ],
            [
                'puzzle_category_id' => $logic->id,
                'title' => 'أشهر السنة',
                'type' => 'text',
                'difficulty' => 'easy',
                'prompt' => 'كم عدد أشهر السنة التي تحتوي على 28 يوماً على الأقل؟',
                'answer_raw' => '12',
                'hint' => 'فكّر بكل شهر، مهما كان عدد أيامه الكلي، هل يحتوي أول 28 يوم منه؟',
                'gem_reward' => 5,
            ],
            [
                'puzzle_category_id' => $logic->id,
                'title' => 'أي يوم اليوم؟',
                'type' => 'text',
                'difficulty' => 'medium',
                'prompt' => 'إذا كان اليوم بعد غد هو يوم الأربعاء، فما هو اليوم الحالي؟',
                'answer_raw' => 'الأحد',
                'hint' => 'بعد غد يعني بعد يومين من اليوم.',
                'gem_reward' => 10,
            ],
            [
                'puzzle_category_id' => $logic->id,
                'title' => 'الرجل قصير القامة',
                'type' => 'multiple_choice',
                'difficulty' => 'hard',
                'prompt' => 'رجل يسكن بالطابق العاشر من عمارة. كل صباح ينزل بالمصعد للأرضي، وعند عودته يستقل المصعد للطابق السابع فقط ثم يكمل الباقي سيراً على الأقدام، إلا بالأيام الممطرة فيصعد مباشرة للطابق العاشر. لماذا؟',
                'choices' => ['طوله لا يصل لزر الطابق العاشر إلا بالمظلة', 'المصعد معطل جزئياً', 'يحب ممارسة الرياضة', 'زر الطابق العاشر مخفي'],
                'answer_raw' => 'طوله لا يصل لزر الطابق العاشر إلا بالمظلة',
                'hint' => 'فكّر بشيء يحمله بيده فقط بالأيام الممطرة.',
                'gem_reward' => 20,
            ],
            [
                'puzzle_category_id' => $logic->id,
                'title' => 'الأخوان وساعة الميلاد',
                'type' => 'multiple_choice',
                'difficulty' => 'medium',
                'prompt' => 'أخوان وُلد أحدهما قبل الآخر بساعة واحدة بالضبط، لكنهما ليسا توأمين. كيف يُعقل ذلك؟',
                'choices' => ['هما اثنان من ثلاثة توائم', 'خطأ في شهادة الميلاد', 'أحدهما بالتبني', 'ولدا في بلدين مختلفي التوقيت'],
                'answer_raw' => 'هما اثنان من ثلاثة توائم',
                'hint' => 'ماذا لو كان هناك أخ ثالث بينهما بالولادة؟',
                'gem_reward' => 15,
            ],
            [
                'puzzle_category_id' => $logic->id,
                'title' => 'مربعات لوحة الشطرنج',
                'type' => 'text',
                'difficulty' => 'hard',
                'prompt' => 'كم عدد المربعات الموجودة بلوحة شطرنج قياسية 8×8، إذا احتسبنا كل الأحجام الممكنة (1×1، 2×2، 3×3... حتى 8×8)؟',
                'answer_raw' => '204',
                'hint' => 'اجمع مربعات كل حجم: 8²+7²+6²+...+1².',
                'gem_reward' => 25,
            ],
            [
                'puzzle_category_id' => $logic->id,
                'title' => 'الكرة الأثقل',
                'type' => 'text',
                'difficulty' => 'medium',
                'prompt' => 'لديك ميزان ذو كفتين، و9 كرات متماثلة الشكل تماماً، واحدة منها فقط أثقل قليلاً من البقية. ما أقل عدد مرات توزين تحتاجها لتحديد الكرة الأثقل بالتأكيد؟',
                'answer_raw' => '2',
                'hint' => 'قسّم الكرات إلى 3 مجموعات متساوية.',
                'gem_reward' => 15,
            ],
            [
                'puzzle_category_id' => $logic->id,
                'title' => 'العدد المحايد بالضرب',
                'type' => 'text',
                'difficulty' => 'easy',
                'prompt' => 'ما هو العدد الذي إذا ضربته في أي عدد آخر، يبقى الناتج هو نفس العدد الآخر بلا تغيير؟',
                'answer_raw' => '1',
                'hint' => 'جرّب ضرب أي رقم به.',
                'gem_reward' => 5,
            ],
            [
                'puzzle_category_id' => $logic->id,
                'title' => 'من في الصورة؟',
                'type' => 'text',
                'difficulty' => 'medium',
                'prompt' => 'رجل ينظر لصورة معلّقة على الحائط ويقول: "لا إخوة لي ولا أخوات، لكن أبو هذا الرجل بالصورة هو ابني." من هو الشخص بالصورة؟',
                'answer_raw' => 'ابنه',
                'hint' => 'إذا كان أبو الشخص بالصورة هو ابن المتحدث، فمن هو الشخص بالصورة بالنسبة للمتحدث؟',
                'gem_reward' => 10,
            ],

            // ===== ألغاز رياضية =====
            [
                'puzzle_category_id' => $math->id,
                'title' => 'المتتالية الناقصة',
                'type' => 'text',
                'difficulty' => 'medium',
                'prompt' => 'أكمل المتتالية: 2، 6، 12، 20، 30، ...؟',
                'answer_raw' => '42',
                'hint' => 'الفرق بين كل رقمين متتاليين يزيد بمقدار 2 كل مرة.',
                'gem_reward' => 10,
            ],
            [
                'puzzle_category_id' => $math->id,
                'title' => 'ترتيب العمليات',
                'type' => 'text',
                'difficulty' => 'easy',
                'prompt' => 'ما ناتج: 7 × 8 - 6 ÷ 2 ؟',
                'answer_raw' => '53',
                'hint' => 'اضرب واقسم أولاً، ثم اطرح.',
                'gem_reward' => 5,
            ],
            [
                'puzzle_category_id' => $math->id,
                'title' => 'عمر الأخوين',
                'type' => 'text',
                'difficulty' => 'easy',
                'prompt' => 'عمر أحمد ضعف عمر أخيه، ومجموع أعمارهما 24 سنة. كم عمر أحمد؟',
                'answer_raw' => '16',
                'hint' => 'اقسم المجموع على 3 أجزاء، ثم خذ الجزأين لأحمد.',
                'gem_reward' => 5,
            ],
            [
                'puzzle_category_id' => $math->id,
                'title' => 'مربعات كاملة',
                'type' => 'text',
                'difficulty' => 'easy',
                'prompt' => 'أكمل المتتالية: 1، 4، 9، 16، 25، ...؟',
                'answer_raw' => '36',
                'hint' => 'كل حد هو مربع رقم صحيح (1²، 2²، 3²...).',
                'gem_reward' => 5,
            ],
            [
                'puzzle_category_id' => $math->id,
                'title' => 'معادلتان بمجهولين',
                'type' => 'text',
                'difficulty' => 'medium',
                'prompt' => 'إذا كان س + ص = 10 و س - ص = 4، فما قيمة س؟',
                'answer_raw' => '7',
                'hint' => 'اجمع المعادلتين معاً واقسم الناتج على 2.',
                'gem_reward' => 10,
            ],
            [
                'puzzle_category_id' => $math->id,
                'title' => 'أوجه المكعب',
                'type' => 'text',
                'difficulty' => 'easy',
                'prompt' => 'كم عدد أوجه المكعب؟',
                'answer_raw' => '6',
                'hint' => 'فكّر بصندوق النرد.',
                'gem_reward' => 5,
            ],
            [
                'puzzle_category_id' => $math->id,
                'title' => 'سرعة القطار',
                'type' => 'text',
                'difficulty' => 'medium',
                'prompt' => 'قطار يقطع 60 كم في الساعة، كم دقيقة يحتاج ليقطع 150 كم؟',
                'answer_raw' => '150',
                'hint' => 'احسب أولاً كم كم يقطع بالدقيقة الواحدة.',
                'gem_reward' => 10,
            ],
            [
                'puzzle_category_id' => $math->id,
                'title' => 'العدد الأولي الزوجي',
                'type' => 'text',
                'difficulty' => 'medium',
                'prompt' => 'ما هو العدد الأولي الزوجي الوحيد؟',
                'answer_raw' => '2',
                'hint' => 'كل الأعداد الأولية الأخرى فردية.',
                'gem_reward' => 10,
            ],
            [
                'puzzle_category_id' => $math->id,
                'title' => 'مجموع الأعداد',
                'type' => 'multiple_choice',
                'difficulty' => 'medium',
                'prompt' => 'ما ناتج جمع أول 10 أعداد طبيعية (من 1 إلى 10)؟',
                'choices' => ['55', '45', '50', '60'],
                'answer_raw' => '55',
                'hint' => '(1+10) × 10 ÷ 2',
                'gem_reward' => 10,
            ],
            [
                'puzzle_category_id' => $math->id,
                'title' => 'فيبوناتشي',
                'type' => 'text',
                'difficulty' => 'hard',
                'prompt' => 'متتالية فيبوناتشي تبدأ: 1، 1، 2، 3، 5، 8... ما هو الحد العاشر بهذه المتتالية؟',
                'answer_raw' => '55',
                'hint' => 'كل حد = مجموع الحدين اللذين قبله.',
                'gem_reward' => 20,
            ],

            // ===== ألغاز لغوية =====
            [
                'puzzle_category_id' => $language->id,
                'title' => 'الحرف المحذوف',
                'type' => 'multiple_choice',
                'difficulty' => 'hard',
                'prompt' => 'أي حرف عربي لا يقبل الوصل بالحرف الذي يليه أبداً من هذه الخيارات؟',
                'choices' => ['الباء', 'الدال', 'السين', 'الكاف'],
                'answer_raw' => 'الدال',
                'hint' => 'من الحروف التي "تكتب منفصلة دائماً" رغم اتصالها بما قبلها.',
                'gem_reward' => 20,
            ],
            [
                'puzzle_category_id' => $language->id,
                'title' => 'جمع قلم',
                'type' => 'text',
                'difficulty' => 'easy',
                'prompt' => 'ما هو جمع كلمة "قلم"؟',
                'answer_raw' => 'أقلام',
                'hint' => 'جمع تكسير على وزن أفعال.',
                'gem_reward' => 5,
            ],
            [
                'puzzle_category_id' => $language->id,
                'title' => 'مفرد كتب',
                'type' => 'text',
                'difficulty' => 'easy',
                'prompt' => 'ما مفرد كلمة "كتب"؟',
                'answer_raw' => 'كتاب',
                'hint' => 'الشيء الذي تقرأه صفحة صفحة.',
                'gem_reward' => 5,
            ],
            [
                'puzzle_category_id' => $language->id,
                'title' => 'ضد كريم',
                'type' => 'text',
                'difficulty' => 'easy',
                'prompt' => 'ما ضد كلمة "كريم" (بمعنى سخي)؟',
                'answer_raw' => 'بخيل',
                'hint' => 'عكس من يعطي بسهولة.',
                'gem_reward' => 5,
            ],
            [
                'puzzle_category_id' => $language->id,
                'title' => 'ترتيب الأبجدية',
                'type' => 'text',
                'difficulty' => 'easy',
                'prompt' => 'ما هو الحرف الذي يأتي مباشرة بعد حرف "السين" بالأبجدية العربية؟',
                'answer_raw' => 'الشين',
                'hint' => 'رتّب الحروف: ...ر ز س ش ص...',
                'gem_reward' => 5,
            ],
            [
                'puzzle_category_id' => $language->id,
                'title' => 'كلمة دخيلة',
                'type' => 'multiple_choice',
                'difficulty' => 'medium',
                'prompt' => 'أي هذه الكلمات ليست من أصل عربي (كلمة دخيلة من لغة أخرى)؟',
                'choices' => ['تلفاز', 'إستراتيجية', 'سيارة', 'كتاب'],
                'answer_raw' => 'إستراتيجية',
                'hint' => 'كلمة يونانية الأصل انتقلت لكثير من اللغات.',
                'gem_reward' => 10,
            ],
            [
                'puzzle_category_id' => $language->id,
                'title' => 'جمع قاضٍ',
                'type' => 'text',
                'difficulty' => 'medium',
                'prompt' => 'ما هو جمع كلمة "قاضٍ"؟',
                'answer_raw' => 'قضاة',
                'hint' => 'جمع تكسير على وزن فُعاة.',
                'gem_reward' => 10,
            ],
            [
                'puzzle_category_id' => $language->id,
                'title' => 'عدد حروف العربية',
                'type' => 'text',
                'difficulty' => 'easy',
                'prompt' => 'كم عدد حروف اللغة العربية (الهجائية)؟',
                'answer_raw' => '28',
                'hint' => 'من الألف إلى الياء.',
                'gem_reward' => 5,
            ],
            [
                'puzzle_category_id' => $language->id,
                'title' => 'علم أوزان الشعر',
                'type' => 'text',
                'difficulty' => 'hard',
                'prompt' => 'ما اسم العلم الذي يهتم بدراسة أوزان الشعر العربي وبحوره؟',
                'answer_raw' => 'العروض',
                'hint' => 'أسسه الخليل بن أحمد الفراهيدي.',
                'gem_reward' => 20,
            ],
            [
                'puzzle_category_id' => $language->id,
                'title' => 'ضد يقظة',
                'type' => 'text',
                'difficulty' => 'medium',
                'prompt' => 'ما ضد كلمة "يقظة"؟',
                'answer_raw' => 'نوم',
                'hint' => 'عكس الانتباه والوعي.',
                'gem_reward' => 10,
            ],

            // ===== ثقافة عامة =====
            [
                'puzzle_category_id' => $general->id,
                'title' => 'قارات العالم',
                'type' => 'text',
                'difficulty' => 'easy',
                'prompt' => 'كم عدد قارات العالم؟',
                'answer_raw' => '7',
                'hint' => 'آسيا، أفريقيا، أوروبا، أمريكا الشمالية، أمريكا الجنوبية، أستراليا، أنتاركتيكا.',
                'gem_reward' => 5,
            ],
            [
                'puzzle_category_id' => $general->id,
                'title' => 'أطول نهر',
                'type' => 'text',
                'difficulty' => 'easy',
                'prompt' => 'ما هي أطول نهر في العالم؟',
                'answer_raw' => 'النيل',
                'hint' => 'يمر بمصر والسودان وعدة دول أفريقية أخرى.',
                'gem_reward' => 5,
            ],
            [
                'puzzle_category_id' => $general->id,
                'title' => 'غزوة بدر',
                'type' => 'text',
                'difficulty' => 'medium',
                'prompt' => 'في أي سنة هجرية وقعت غزوة بدر الكبرى؟',
                'answer_raw' => '2',
                'hint' => 'كانت بعد الهجرة بعامين.',
                'gem_reward' => 10,
            ],
            [
                'puzzle_category_id' => $general->id,
                'title' => 'عاصمة اليابان',
                'type' => 'multiple_choice',
                'difficulty' => 'easy',
                'prompt' => 'ما هي عاصمة اليابان؟',
                'choices' => ['طوكيو', 'بكين', 'سول', 'بانكوك'],
                'answer_raw' => 'طوكيو',
                'hint' => 'أكبر مدينة يابانية أيضاً.',
                'gem_reward' => 5,
            ],
            [
                'puzzle_category_id' => $general->id,
                'title' => 'أركان الإسلام',
                'type' => 'text',
                'difficulty' => 'easy',
                'prompt' => 'كم عدد أركان الإسلام؟',
                'answer_raw' => '5',
                'hint' => 'الشهادتان، الصلاة، الزكاة، الصوم، الحج.',
                'gem_reward' => 5,
            ],
            [
                'puzzle_category_id' => $general->id,
                'title' => 'أكبر محيط',
                'type' => 'multiple_choice',
                'difficulty' => 'medium',
                'prompt' => 'ما هو أكبر محيط في العالم من حيث المساحة؟',
                'choices' => ['المحيط الهادئ', 'المحيط الأطلسي', 'المحيط الهندي', 'المحيط المتجمد الشمالي'],
                'answer_raw' => 'المحيط الهادئ',
                'hint' => 'يفصل بين آسيا والأمريكتين.',
                'gem_reward' => 10,
            ],
            [
                'puzzle_category_id' => $general->id,
                'title' => 'مخترع المصباح',
                'type' => 'multiple_choice',
                'difficulty' => 'medium',
                'prompt' => 'من يُنسب له اختراع المصباح الكهربائي (بصورته العملية الأولى)؟',
                'choices' => ['توماس إديسون', 'نيكولا تسلا', 'ألكسندر بيل', 'بنجامين فرانكلين'],
                'answer_raw' => 'توماس إديسون',
                'hint' => 'مخترع أمريكي أسس شركة جنرال إلكتريك لاحقاً.',
                'gem_reward' => 10,
            ],
            [
                'puzzle_category_id' => $general->id,
                'title' => 'عظام الجسم',
                'type' => 'text',
                'difficulty' => 'hard',
                'prompt' => 'كم عدد عظام جسم الإنسان البالغ؟',
                'answer_raw' => '206',
                'hint' => 'الطفل يولد بعدد أكبر ثم تلتحم بعض العظام مع النمو.',
                'gem_reward' => 20,
            ],
            [
                'puzzle_category_id' => $general->id,
                'title' => 'أصغر دولة',
                'type' => 'text',
                'difficulty' => 'medium',
                'prompt' => 'ما هي أصغر دولة في العالم من حيث المساحة؟',
                'answer_raw' => 'الفاتيكان',
                'hint' => 'تقع داخل مدينة روما الإيطالية.',
                'gem_reward' => 10,
            ],
            [
                'puzzle_category_id' => $general->id,
                'title' => 'مؤلف المقدمة',
                'type' => 'text',
                'difficulty' => 'hard',
                'prompt' => 'من هو مؤلف كتاب "المقدمة" الشهير في علم الاجتماع والتاريخ؟',
                'answer_raw' => 'ابن خلدون',
                'hint' => 'يُلقّب بأبي علم الاجتماع.',
                'gem_reward' => 20,
                'is_daily_puzzle' => true,
                'daily_puzzle_date' => now()->toDateString(),
            ],

            // ===== ألغاز الصور (تصور بصري/مكاني، بدون صور فعلية) =====
            [
                'puzzle_category_id' => $visual->id,
                'title' => 'مثلثات المربع',
                'type' => 'text',
                'difficulty' => 'easy',
                'prompt' => 'تخيّل مربعاً رسمت قطريه الاثنين. كم مثلثاً يتكوّن بالضبط داخل المربع؟',
                'answer_raw' => '4',
                'hint' => 'كل قطر يقسم المربع لجزأين، والقطران معاً...',
                'gem_reward' => 5,
            ],
            [
                'puzzle_category_id' => $visual->id,
                'title' => 'أضلاع السداسي',
                'type' => 'text',
                'difficulty' => 'easy',
                'prompt' => 'كم عدد أضلاع الشكل السداسي المنتظم؟',
                'answer_raw' => '6',
                'hint' => 'اسمه يدل على العدد.',
                'gem_reward' => 5,
            ],
            [
                'puzzle_category_id' => $visual->id,
                'title' => 'الألوان الأساسية',
                'type' => 'text',
                'difficulty' => 'easy',
                'prompt' => 'كم عدد الألوان الأساسية التي لا يمكن الحصول عليها بمزج ألوان أخرى (الأحمر، الأزرق، الأصفر)؟',
                'answer_raw' => '3',
                'hint' => 'منها تُصنع باقي الألوان بالمزج.',
                'gem_reward' => 5,
            ],
            [
                'puzzle_category_id' => $visual->id,
                'title' => 'وجوه الهرم الرباعي',
                'type' => 'text',
                'difficulty' => 'medium',
                'prompt' => 'كم عدد الأوجه الكلية لهرم قاعدته مربعة (بما فيها القاعدة)؟',
                'answer_raw' => '5',
                'hint' => 'قاعدة واحدة + أربعة أوجه جانبية مثلثة.',
                'gem_reward' => 10,
            ],
            [
                'puzzle_category_id' => $visual->id,
                'title' => 'الشكل بدون تساوي أضلاع',
                'type' => 'multiple_choice',
                'difficulty' => 'medium',
                'prompt' => 'أي من هذه الأشكال ليس بالضرورة متساوي الأضلاع؟',
                'choices' => ['مستطيل', 'مربع', 'معين', 'مثلث متساوي الأضلاع'],
                'answer_raw' => 'مستطيل',
                'hint' => 'فكّر بمستطيل طويل وضيق جداً.',
                'gem_reward' => 10,
            ],
            [
                'puzzle_category_id' => $visual->id,
                'title' => 'محاور تماثل الدائرة',
                'type' => 'multiple_choice',
                'difficulty' => 'hard',
                'prompt' => 'كم عدد محاور التماثل التي تمتلكها الدائرة الكاملة؟',
                'choices' => ['عدد لا نهائي', '4', '1', '0'],
                'answer_raw' => 'عدد لا نهائي',
                'hint' => 'أي خط يمر بالمركز يقسمها لنصفين متطابقين.',
                'gem_reward' => 20,
            ],
            [
                'puzzle_category_id' => $visual->id,
                'title' => 'أوجه المكعب المرئية',
                'type' => 'text',
                'difficulty' => 'medium',
                'prompt' => 'عند رسم مكعب برسم ثلاثي الأبعاد قياسي (بزاوية واحدة كما يُرسم عادة)، كم وجهاً منه يظهر للناظر عادة؟',
                'answer_raw' => '3',
                'hint' => 'فكّر بزاوية النظر المعتادة لصندوق.',
                'gem_reward' => 10,
            ],
            [
                'puzzle_category_id' => $visual->id,
                'title' => 'لون قوس قزح الأوسط',
                'type' => 'text',
                'difficulty' => 'medium',
                'prompt' => 'ألوان قوس قزح السبعة بترتيبها المعروف (أحمر، برتقالي، أصفر، أخضر، أزرق، نيلي، بنفسجي)، ما هو اللون الرابع (الأوسط)؟',
                'answer_raw' => 'أخضر',
                'hint' => 'عدّ من البداية: 1 أحمر، 2 برتقالي، 3 أصفر، 4...؟',
                'gem_reward' => 10,
            ],
            [
                'puzzle_category_id' => $visual->id,
                'title' => 'زوايا المثلث',
                'type' => 'text',
                'difficulty' => 'easy',
                'prompt' => 'كم عدد زوايا المثلث؟',
                'answer_raw' => '3',
                'hint' => 'اسمه يدل على العدد أيضاً.',
                'gem_reward' => 5,
            ],
            [
                'puzzle_category_id' => $visual->id,
                'title' => 'مجموع زوايا المثلث',
                'type' => 'text',
                'difficulty' => 'hard',
                'prompt' => 'كم يساوي مجموع زوايا أي مثلث (بالدرجات)؟',
                'answer_raw' => '180',
                'hint' => 'قاعدة هندسية أساسية ثابتة لكل مثلث.',
                'gem_reward' => 20,
            ],
        ];

        foreach ($samples as $sample) {
            Puzzle::firstOrCreate(['title' => $sample['title']], $sample);
        }

        $this->command->info('تمت إضافة '.count($samples).' أحجية تجريبية موزّعة على كل التصنيفات.');
    }
}